#spring.application.name=TrainerEffort
#server.port=8085
#spring.cloud.compatibility-verifier.enabled=false
#
#spring.datasource.url=jdbc:mysql://localhost:3306/effort
#spring.datasource.username=root
#spring.datasource.password=Krupa@#27
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#
#logging.level.feign.client = DEBUG

spring.application.name=trainereffort
server.port=${PORT:8085}

spring.cloud.compatibility-verifier.enabled=false

# PostgreSQL Database (Neon)
spring.datasource.url=jdbc:postgresql://ep-patient-sky-a49ilhak-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_LbDg8KM6icGj
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- EUREKA CONNECTION ---
# Point to your actual live registry
eureka.client.service-url.defaultZone=https://serviceregistry-1-p6w0.onrender.com/eureka/

# Render Networking (Public URL routing)
eureka.instance.hostname=${RENDER_EXTERNAL_HOSTNAME}
eureka.instance.prefer-ip-address=false

# Force Secure Communication
eureka.instance.non-secure-port-enabled=false
eureka.instance.secure-port-enabled=true
eureka.instance.secure-port=443